{
  stdenv,
  lib,
  fetchFromGitHub,
  cmake,
  autoPatchelfHook,
  glfw,
  SDL2,
  alsa-lib,
  libpulseaudio,
  libGLU,
  libX11,
  curl, # Non-raylib
  platform ? "Desktop",
  pulseSupport ? stdenv.hostPlatform.isLinux,
  alsaSupport ? false,
  sharedLib ? true,
  includeEverything ? true,
}: let
  pname = "temp-c-raylib";
  inherit (lib) optional;
  raylib = fetchFromGitHub {
    owner = "raysan5";
    repo = "raylib";
    rev = "5.5";
    hash = "sha256-J99i4z4JF7d6mJNuJIB0rHNDhXJ5AEkG0eBvvuBLHrY=";
  };
in lib.checkListOfEnum "${pname}: platform"
  [ # Basically no testing has been done yet
    "Desktop"
    "Web"
    "Android"
    "Raspberry Pi"
    "DRM"
    "SDL"
  ]
  [ platform ] # Note that "Web", "Android" and "Raspberry Pi" do not currently work
( stdenv.mkDerivation (finalAttrs: {
  inherit pname;
  version = "4.0.0";
  src = ./.;

  # autoPatchelfHook is needed for appendRunpaths
  nativeBuildInputs = [
    curl cmake
  ] ++ optional (builtins.length finalAttrs.appendRunpaths > 0) autoPatchelfHook;

  buildInputs = optional (platform == "Desktop") glfw ++ optional (platform == "SDL") SDL2;
  propagatedBuildInputs = lib.optionals stdenv.hostPlatform.isLinux [
    libGLU
    libX11
    # libXcursor
    # libXrandr
    # libXinerama
    # libXi
  ];

  # Set up local copies of required submodules.
  preConfigure = ''
    echo "Copying raylib source to local writable directory..."
    mkdir -p build
    cp -r ${raylib} build/raylib-source
    chmod -R u+w build/raylib-source

    echo "Setting up cmake directory"
    echo '#include "../../../src/temp-c-raylib.c"' >> build/raylib-source/src/rcore.c
    echo `ls build/`
    echo `ls build/raylib-source`
    echo `ls build/raylib-source/src`
  '';

  patchPhase = ''
    echo `grep -rI "^#\! */bin/sh" .`
  '';
  cmakeDir = "raylib-source";

  appendRunpaths = optional stdenv.hostPlatform.isLinux (
    lib.makeLibraryPath (optional alsaSupport alsa-lib ++ optional pulseSupport libpulseaudio)
  );

  # https://github.com/raysan5/raylib/wiki/CMake-Build-Options
  cmakeFlags =
    [
      "-DCUSTOMIZE_BUILD=ON"
      "-DPLATFORM=${platform}"
      "-DBUILD_EXAMPLES=OFF"
    ]
    ++ optional (platform == "Desktop") "-DUSE_EXTERNAL_GLFW=ON"
    ++ optional includeEverything "-DINCLUDE_EVERYTHING=ON"
    ++ optional sharedLib "-DBUILD_SHARED_LIBS=ON";



  meta = {
    description = "Autogenerated changes to raylib, for fixing functions so they work for ⎕NA in Dyalog APL";
    homepage    = "https://github.com/Brian-ED/temp-c-raylib";
    license     = lib.licenses.mit;
    platforms   = lib.platforms.all;
  };
}))
